[workspace]
resolver = "2"

members = [
    "crates/redstone",
    "crates/redstone_testing"
]


[patch.crates-io.curve25519-dalek]
git = "https://github.com/solana-labs/curve25519-dalek.git"
rev = "b500cdc2a920cd5bff9e2dd974d7b97349d61464"
