[package]
edition = "2021"
name = "redstone-testing"
version = "0.3.0"

[features]
radix = ["redstone/radix"]
solana = ["redstone/solana"]

[dependencies]
hex = "0.4.3"
redstone = { git = "https://github.com/redstone-finance/rust-sdk", tag = "3.0.0-pre3", default-features = false }
